/********************************************************************
* ../src/RawEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/RawEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableRawEventDict();
extern void G__cpp_setup_inheritanceRawEventDict();
extern void G__cpp_setup_typetableRawEventDict();
extern void G__cpp_setup_memvarRawEventDict();
extern void G__cpp_setup_globalRawEventDict();
extern void G__cpp_setup_memfuncRawEventDict();
extern void G__cpp_setup_funcRawEventDict();
extern void G__set_cpp_environmentRawEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RawEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RawEventDictLN_TClass;
extern G__linked_taginfo G__RawEventDictLN_TBuffer;
extern G__linked_taginfo G__RawEventDictLN_TMemberInspector;
extern G__linked_taginfo G__RawEventDictLN_TObject;
extern G__linked_taginfo G__RawEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RawEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RawEventDictLN_JM;
extern G__linked_taginfo G__RawEventDictLN_JMcLcLRawEvent;

/* STUB derived class for protected member access */
